### ISSUE TITLE
feat: add bulk method to hyper63 client nodejs

### ISSUE THREAD

**Issue by twilson63** [hyper63/hyper63#145]
As a client, I want to call the bulk data endpoint and send an array of documents to the data store

``` js
client.data.bulk([...])
  .fork(
     e => console.log(e),
     r => console.log('results', r)
  )
```

## Task

- [ ] implement in core
- [ ] happy test path
- [ ] sad test path
